[build]
  functions = "netlify/functions"
  publish = "."

[functions]
  # Directory for serverless functions
  directory = "netlify/functions"

[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"

[[redirects]]
  from = "/api/calendar"
  to = "/.netlify/functions/calendar"
  status = 200

[[redirects]]
  from = "/api/ping"  
  to = "/.netlify/functions/ping"
  status = 200